# Generated by Django 3.1.2 on 2020-10-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
