# Generated by Django 3.1.2 on 2020-10-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0002_auto_20201012_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
