# Generated by Django 3.1.2 on 2020-10-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0003_auto_20201012_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameImage', models.CharField(max_length=140, null=True)),
                ('uploadedImage', models.ImageField(null=True, upload_to='Upload/')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
