# Generated by Django 3.1.2 on 2020-10-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0004_auto_20201012_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='nameImage',
        ),
    ]
