# Generated by Django 3.1.2 on 2020-10-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0005_remove_upload_nameimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='quality',
            field=models.IntegerField(default=0),
        ),
    ]
