# Generated by Django 3.1.2 on 2020-10-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0006_upload_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='uploadedImage',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='upload',
            name='quality',
            field=models.IntegerField(blank=True, default=40, help_text='Enter the number between 0 to 100, lower number=higher compression.'),
        ),
    ]
