# Generated by Django 3.1.2 on 2020-10-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0010_auto_20201013_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='quality',
            field=models.IntegerField(help_text='Enter the number between 0 to 100, lower number=higher compression.'),
        ),
    ]
