# Generated by Django 3.1.2 on 2020-10-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0011_auto_20201013_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='quality',
        ),
    ]
