# Generated by Django 3.1.2 on 2020-10-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0013_upload_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='quality',
        ),
    ]
