# Generated by Django 3.1.2 on 2020-10-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0014_remove_upload_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
