# Generated by Django 3.1.2 on 2020-10-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0015_upload_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='session_id',
        ),
    ]
