# Generated by Django 3.1.2 on 2020-10-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0016_remove_upload_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='upload',
            name='token',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='size_reducer.token'),
        ),
    ]
