# Generated by Django 3.1.2 on 2020-10-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0017_auto_20201016_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token',
        ),
    ]
