# Generated by Django 3.1.2 on 2020-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size_reducer', '0018_remove_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
